### ISSUE TITLE
Update default sel4.toml settings

### ISSUE THREAD

**Issue by pittma** [auxoncorp/selfe-sys#4]
1. The [seL4 dependencies](https://github.com/auxoncorp/ferros/blob/ad3807bcd7a98bfc1f487a24339a7d2670ad4f3c/sel4.toml#L21-L26).
```toml
[sel4]
# We need some of the changes since last release for TX1/aarch64 hyp support
# These refs are from master as of 10MAY2019
kernel = { git = "https://github.com/seL4/seL4" , rev = "4d0f02c029560cae0e8d93727eb17d58bcecc2ac" }
tools = { git = "https://github.com/seL4/seL4_tools" , rev = "f3b4bef672b92858c139787bc6fd5124e6022d26" }
util_libs  = { git = "https://github.com/seL4/util_libs" , rev = "98aaebe56c66d46576485216f8c4626ed76a3757" }
```
1. A TX1 config which uses aarch64: See [here](https://github.com/auxoncorp/ferros/blob/ad3807bcd7a98bfc1f487a24339a7d2670ad4f3c/sel4.toml#L10-L19) and [here](https://github.com/auxoncorp/ferros/blob/ad3807bcd7a98bfc1f487a24339a7d2670ad4f3c/sel4.toml#L36-L48).

---

https://github.com/auxoncorp/ferros/issues/9 results in Ferros supporting both architectures, it's this capability which spurred the need for new defaults.
